### ISSUE TITLE
Respuesta endpoint `/recognize/raw`

### ISSUE THREAD

**Issue by agarsev** [agarsev/visse-app#3]
El nuevo endpoint `/recognize/raw` no puede devolver directamente el Logograma ya que no es serializable, supongo que por los datos de la imagen etc. Por otro lado, antes de devolver la respuesta hay que ejecutar el pipeline para que reconozca los grafemas en la imagen.

Es decir, para mejorar el nuevo que código y que funcione, habría que:

- [x] Cambiar nombre función `recognize_tfg_signos` por `recognize_raw`
- [x] Incluir copia de las líneas 159--165 que llaman al pipeline y miden cuánto tarda
- [x] Usar la función [`to_dict()`](https://agarsev.github.io/quevedo/latest/api/#quevedoannotationlogogramlogogramto_dict) del logograma para convertirlo a un diccionario antes de enviarlo
- [x] Usar [`JSONResponse`](https://fastapi.tiangolo.com/advanced/response-directly/) de FastAPI para enviar el json como respuesta

**Comment by pfolgueira** [comment]
Ya solucionado en la nueva rama "tfg-2425-signos". Hemos estado probándolo y funciona bien, muchas gracias.

**Comment by agarsev** [comment]
Perfecto, mezclado 👍🏻
